//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AplicacionWebASP.NetClase02.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_empleado
    {
        public int idEmpleado { get; set; }
        public string Emple_Nombre { get; set; }
        public string Emple_DUI { get; set; }
        public string Emple_direccion { get; set; }
        public string Emple_tel { get; set; }
        public string Emple_email { get; set; }
        public string Emple_cargo { get; set; }
    }
}
